vich_uploader:
  db_driver: orm

  mappings:
    resources:
      uri_prefix: /imgs/products
      upload_destination: "%kernel.project_dir%/public/imgs/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
